[build]
builder = "NIXPACKS"
# Install root, client, and server deps before building
buildCommand = """
npm install
cd client && npm install && cd ..
cd server && npm install && cd ..
npm run build
"""
